steps:
# Run tests
- name: 'golang:latest'
  args:
  - go
  - test
  - -v
  - ./...
  env:
  - 'GO111MODULE=on'
  - 'CGO_ENABLED=0'

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -f
  - Dockerfile
  - --network
  - cloudbuild
  - --build-arg
  - VERSION=$SHORT_SHA
  - -t
  - gcr.io/$PROJECT_ID/github.com/refractionpoint/lc-mcp-server:$SHORT_SHA
  - .
options:
 machineType: 'E2_HIGHCPU_8'
