# Google Cloud Build configuration for LimaCharlie MCP Server (Go)
#
# This build:
# 1. Runs tests
# 2. Builds a distroless container image
# 3. Pushes to Artifact Registry
# 4. Optionally deploys to Cloud Run
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml
#
# With substitutions:
#   gcloud builds submit --config=cloudbuild.yaml \
#     --substitutions=_SERVICE_NAME=lc-mcp-server,_REGION=us-central1

steps:
  # Step 1: Run tests
  - name: 'golang:1.23'
    id: 'test'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running tests..."
        go test -v -race -cover ./...
        echo "Tests passed!"

  # Step 2: Build and push container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    waitFor: ['test']

  # Step 3: Push container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}'
    waitFor: ['build']

  # Step 4: Deploy to Cloud Run (optional - comment out if not using Cloud Run)
  # Uncomment the section below to enable automatic deployment
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy'
  #   entrypoint: 'gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - '${_SERVICE_NAME}'
  #     - '--image'
  #     - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
  #     - '--region'
  #     - '${_REGION}'
  #     - '--platform'
  #     - 'managed'
  #     - '--allow-unauthenticated'
  #     - '--set-env-vars'
  #     - 'MCP_MODE=stdio,MCP_PROFILE=all,LOG_LEVEL=info'
  #     - '--memory'
  #     - '512Mi'
  #     - '--cpu'
  #     - '1'
  #     - '--min-instances'
  #     - '0'
  #     - '--max-instances'
  #     - '10'
  #     - '--concurrency'
  #     - '80'
  #     - '--timeout'
  #     - '300s'
  #   waitFor: ['push']

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'

# Build options
options:
  # Use higher CPU machine for faster builds
  machineType: 'E2_HIGHCPU_8'

  # Enable Docker layer caching
  substitutionOption: 'ALLOW_LOOSE'

  # Build logs
  logging: CLOUD_LOGGING_ONLY

  # Timeout for entire build
  timeout: '1200s'

# Default substitution values
substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'lc-mcp-server'
  _IMAGE_NAME: 'lc-mcp-server'
  _SERVICE_NAME: 'lc-mcp-server'

# Tags for organization
tags:
  - 'lc-mcp-server'
  - 'go-port'
  - 'distroless'
