version: '3.8'

services:
  # LimaCharlie MCP Server
  mcp-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Server mode
      - PUBLIC_MODE=true
      - MCP_OAUTH_ENABLED=true

      # Server configuration
      - MCP_SERVER_URL=http://localhost:8080
      - MCP_PROFILE=all

      # Redis configuration
      - REDIS_URL=redis://redis:6379

      # Firebase configuration (set your Firebase API key)
      - FIREBASE_API_KEY=${FIREBASE_API_KEY:-}

      # Optional: GCS configuration for large results
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-}
      - GCS_URL_EXPIRY_HOURS=24
      - GCS_TOKEN_THRESHOLD=1000

      # Optional: AI features
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - mcp-network

  # Redis for OAuth state management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - mcp-network

volumes:
  redis-data:
    driver: local

networks:
  mcp-network:
    driver: bridge
